server:
  port: 80

spring:
  application:
    name: gateway
zuul:
  routes:
    addition:
      path: /add/**
      serviceId: add
    subtraktion:
      path: /sub/**
      serviceId: sub
    multiplikation:
      path: /mult/**
      serviceId: mult
    division:
      path: /div/**
      serviceId: div

eureka:
  instance:
    metadataMap:
       management.port: ${management.server.port}
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 20000